name: Build & Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.17.0", "18.x"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Bootstrap Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - if: success()
        name: Set final workflow success status
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{github.workflow}}
          description: "Passed"
          state: ${{ job.status }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
      - if: failure()
        name: Set final workflow fail status
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{github.workflow}}
          description: "Failed"
          state: ${{ job.status }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
